class Autogenerated {
  List<Massages>? massages;

  Autogenerated({this.massages});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['massages'] != null) {
      massages = <Massages>[];
      json['massages'].forEach((v) {
        massages!.add(new Massages.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.massages != null) {
      data['massages'] = this.massages!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}


class Massages {

  String? text;
  String? sender;
  String? time;

  Massages({this.text, this.sender, this.time});

  Massages.fromJson(Map<String, dynamic> json) {
    text = json['text'];
    sender = json['sender'];
    time = json['time'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['text'] = this.text;
    data['sender'] = this.sender;
    data['time'] = this.time;
    return data;
  }
}